#pragma once

#include "ActionManager/TweenFunction.h"
#include "ActionManager/Action.h"
#include "ActionManager/ActionEase.h"
#include "ActionManager/ActionInstant.h"
#include "ActionManager/ActionInterval.h"
#include "ActionManager/ActionManager.h"
#include "ActionManager/Array.h"

//Action Instant
#include "ActionManager/ActionInstant/CallFunc.h"
#include "ActionManager/ActionInstant/VisibilityAction.h"

//Action Interval
#include "ActionManager/ActionInterval/BezierAction.h"
#include "ActionManager/ActionInterval/DelayTime.h"
#include "ActionManager/ActionInterval/MoveAction.h"
#include "ActionManager/ActionInterval/RepeatAction.h"
#include "ActionManager/ActionInterval/RotateAction.h"
#include "ActionManager/ActionInterval/SkewAction.h"
#include "ActionManager/ActionInterval/ScaleAction.h"
#include "ActionManager/ActionInterval/Sequence.h"
#include "ActionManager/ActionInterval/Spawn.h"
#include "ActionManager/ActionInterval/TintAction.h"
#include "ActionManager/ActionInterval/ActionFloat.h"
#include "ActionManager/ActionInterval/ActionVec3.h"
#include "ActionManager/ActionInterval/ActionVec4.h"
#include "ActionManager/ActionInterval/FadeAction.h"

//Easings
#include "ActionManager/ActionInterval/Easings/EaseBack.h"
#include "ActionManager/ActionInterval/Easings/EaseBezierAction.h"
#include "ActionManager/ActionInterval/Easings/EaseBounce.h"
#include "ActionManager/ActionInterval/Easings/EaseCircle.h"
#include "ActionManager/ActionInterval/Easings/EaseCubic.h"
#include "ActionManager/ActionInterval/Easings/EaseElastic.h"
#include "ActionManager/ActionInterval/Easings/EaseExponential.h"
#include "ActionManager/ActionInterval/Easings/EaseIn.h"
#include "ActionManager/ActionInterval/Easings/EaseInOut.h"
#include "ActionManager/ActionInterval/Easings/EaseOut.h"
#include "ActionManager/ActionInterval/Easings/EaseQuadratic.h"
#include "ActionManager/ActionInterval/Easings/EaseQuartic.h"
#include "ActionManager/ActionInterval/Easings/EaseQuintic.h"
#include "ActionManager/ActionInterval/Easings/EaseSineIn.h"
#include "ActionManager/ActionInterval/Easings/EaseSineInOut.h"
#include "ActionManager/ActionInterval/Easings/EaseSineOut.h"

#include "Timer.h"
#include "AutoReleasePool.h"
#include "Label.h"
#include "Node.h"
#include "Sprite.h"
#include "ofxCocos.h"
#include "ofxCocosTypes.h"
#include "Ref.h"
#include "TextureCache.h"
#include "ofxCocosTypes.h"
#include "ThreadedLoader.h"
